<?php
/**
 * Introduce ：基础控制器
 * Created by Zyp.
 * Date: 2018/9/27
 */

namespace app\controllers;

use SqlTranslator\Trace;
use yii\web\Controller;

Class BaseController extends Controller
{
    public $params = '';
    private $user;
    /* json格式输出 */
    public function echoJson($status, $list, $code = '200')
    {
        $array = [
            'status' => $status,
            'code' => $code,
            'timestamp' => date('Y-m-d H:i:s', time()),
        ];

        array_key_exists('page', $list) && $array['page'] = $list['page'];
        array_key_exists('pager', $list) && $array['pager'] = $list['pager'];
        array_key_exists('count', $list) && $array['count'] = $list['count'];

        if ($status) {
            $array['date'] = array_filter($list);
        } else {
            $array['error'] = $list;
        }

        if (YII_DEBUG) {
            $array['DEBUG']['_POST'] = $_POST;
            $array['DEBUG']['_GET']  = $_GET;
            /* sqltranslator 获得sql执行条数 */
            $array['DEBUG']['_SQLTrack'] = (new Trace())->getLog();
        }

        return json_encode($array);
    }

    public function beforeAction($action)
    {
        /* 设置头信息避免跨域 */

        $allow_headers = [
            'Content-Type',         #多媒体类型
            'Accept',               #
            'Authorization',
            'X-Requested-With'
        ];

        if (isset($_SERVER['HTTP_ORIGIN'])) {
            header("Access-Control-Allow-Credentials:true");
            header("Access-Control-Allow-Origin:" . $_SERVER['HTTP_ORIGIN']);
        }
        header('Access-Control-Allow-Methods: POST, GET, PUT');
        header('Access-Control-Allow-Headers: ' . implode(', ', $allow_headers));


        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function __get($name)
    {
        return parent::__get($name); // TODO: Change the autogenerated stub
    }

    public function __set($name, $value)
    {
        parent::__set($name,$value);
    }
}